import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { NextPageWithLayout } from "../_app";
import { AdminLayout } from "../../components/admin/adminLayout";
import { trpc } from "../../utils/trpc";

const AdminQuestion: NextPageWithLayout = () => {
    const questionsData = trpc.admin.getAllQuestions.useQuery();
    const questions = questionsData.data?.questions;

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col w-full p-16">
                <h1 className="text-4xl font-bold text-center">Otázky</h1>

                {questions.map(question => (
                    <p>{question.questionText}</p>
                ))}
            </main>
        </>
    );
};

AdminQuestion.Layout = AdminLayout;

export default AdminQuestion;
