import { GetServerSideProps, type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { NextPageWithLayout } from "../_app";
import { AdminLayout } from "../../components/admin/adminLayout";
import { trpc } from "../../utils/trpc";
import { getServerAuthSession } from "../../server/common/get-server-auth-session";
import { Question } from "@prisma/client";
import { QuestionEdit } from "../../components/admin/questionEdit";
import Plus from "./../../components/svg/plus.svg";
import { Toolbar } from "../../components/admin/toolbar";

export const getServerSideProps: GetServerSideProps = async (ctx) => {
    const session = await getServerAuthSession(ctx);

    if (!session) {
        return {
            redirect: {
                destination: '/',
                permanent: false,
            },
        };
    }

    return {
        props: { session },
    };
};

const AdminQuestion: NextPageWithLayout = () => {
    const questionsData = trpc.admin.getAllQuestions.useQuery();
    const questions = questionsData.data?.questions;
    const utils = trpc.useContext();

    const newMutation = trpc.admin.newQuestion.useMutation({
        onSuccess() {
            utils.admin.getAllQuestions.invalidate()
        },
    });

    const newQuestion = () => {
        newMutation.mutate({
            questionText: "Text otázky",
            languageLevel: 0,
            pointAmount: 1,
            rightAnswer: "Správná odpověď",
            wrongAnswers: ["Špatná odpověď 1", "Špatná odpověď 2", "Špatná odpověď 3"],
        });
    }

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col w-full p-16">
                <h1 className="text-4xl font-bold text-center pb-10">Otázky</h1>
                <div className="flex flex-row">
                    <div className="w-full">
                        <QuestionsListing questions={questions} />

                        <div>
                            <button onClick={() => newQuestion()}>vytvořit otázku</button>
                        </div>
                    </div>
                    <div className="flex flex-col mx-auto ml-10 w-32">
                        <Toolbar addCallback={() => console.log("hoj")} saveCallback={() => console.log("yo")}/>
                    </div>
                </div>
            </main>
        </>
    );
};

type QuestionsListingProps = {
    questions: Question[] | undefined
};

const QuestionsListing: React.FC<QuestionsListingProps> = (props) => {
    const {
        questions,
    } = props;

    if (!questions) return (
        <>
            unable to load questions, call Kubík, something went wrong :p
        </>
    );

    return (
        <div className="flex flex-col ">
            {questions.map(question => (
                <QuestionEdit question={question}/>
            ))}
        </div>
    );
}

AdminQuestion.Layout = AdminLayout;

export default AdminQuestion;
